version: '3'
services:
  postgres:
    container_name: final-year-project-flask
    image: postgres:latest
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpwd
      POSTGRES_DB: flaskdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data: